### ISSUE TITLE
Attempted to load class "Database" from namespace

### ISSUE THREAD

**Issue by LeoLR** [evseevnn/php-cassandra-binary#69]
Hi,

I try to use the php cassandra binary, but i've some problems... I'm new on symfony and when i write :

>$nodes = ['127.0.0.1'];
>$database = new evseevnn\Cassandra\Database($nodes, 'keyspace');

I've this error:
>Attempted to load class "Database" from namespace "Projet\HomepageBundle\Controller\evseevnn\Cassandra".
>Did you forget a "use" statement for "evseevnn\Cassandra\Database"

If anyone have a idea? 

Thanks!

**Comment by TomK** [comment]
Try putting a backslash before the fully qualified namespace:
```
$nodes = ['127.0.0.1'];
$database = new \evseevnn\Cassandra\Database($nodes, 'keyspace');
```

**Comment by LeoLR** [comment]
Thank you, that work's!

**Comment by TomK** [comment]
@LeoLR no problem, happy to help
